### ISSUE TITLE
Tagging releases on Docker Hub

### ISSUE THREAD

**Issue by frostbytten** [APSIMInitiative/APSIM.Docker#4]
I was wondering if it was possible to tag releases on Docker Hub so some tooling I am working on can be pinned to a version of APSIM for consistency. Using `:latest`  changes versions on me when we build the pipeline.

**Comment by hol353** [comment]
Some of our docker images do have versions e.g. apsimng, apsimng-complete. Which image are you using?

**Comment by frostbytten** [comment]
I am going to close this issue. Apparently there was an infrastructure issue with  Docker Hub and no versions but latest were available. I see them now.
