### ISSUE TITLE
Error building/running docker images on M1 Mac

### ISSUE THREAD

**Issue by wronk** [APSIMInitiative/APSIM.Docker#9]
Hi @hol353, I'm having issues getting APSIM running within docker. My overall goal is to be able to batch process a series of .apsimx files by repeatedly executing a APSIM Docker container. 

I'll admit I was a little lost without a README, so let me know if there are docker docs somewhere else. From the comments in the `Dockerfile`s, it seemed like this is a multi-step build (see workflow below). I'm happy to help put together a simple README file and PR it if I can get this working.

## Workflow
Currently, I'm doing the following:

```
# Build the `apsimng-build` image
cd /my/work/dir/APSIMInitiative/APSIM.Docker/NextGen/apsimng-build
docker build -t apsiminitiative/apsimng-build .

# Build the `apsimng` image
cd/my/work/dir/APSIMInitiative/APSIM.Docker/NextGen/apsimng
docker build -t apsiminitiative/apsimng .

# cd to the ApsimX directory, and hit the docker entrypoint
cd /my/work/dir/APSIMInitiative/ApsimX
docker run -i --rm -v "$PWD:/apsim" \
apsiminitiative/apsimng \
test_simulation_file.apsimx
```

## Error
On the last line, I get this error
`qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`

From some poking around, it seems like this may be an issue with me building the images on an M1 Mac (with an ARM processor). However, I tried to force build the images for a more typical platform (by adding the `--platform=linux/amd64` flag to `FROM` statements), but that didn't work for me either. I'd hit issues installing `gtk-sharp3`, and wasn't able to fix it from the logs.

## Guidance
Any tips on the docker build process or if Apple silicon is supported?

**Comment by hol353** [comment]
Hi @wronk, the lack of documentation is a real problem and we'd be happy for you to contribute a readme file.

You docker commands look right to me. I suspect it is a problem with the ARM architecture. I'm not a Mac user so I'm tagging a couple of people who may be able to help - @her123 and @zur003

**Comment by wronk** [comment]
Thanks @hol353! 

The first thing I tried was looking for the image on dockerhub. However I wasn't able to find it and thus proceeded to try and build it myself. I must've had a typo though as I see it there now 🤷 I'm was able to pull that image and execute the command. 

In the long term, I will likely not be running this Apple silicon. @her123, @zur003, feel free to save your time

Is there a simple .apsimx file you like for smoke tests? Even though I'm not able to build from scratch, perhaps I can write a basic hello world example on how to pull the image, clone the ApsimX repo, and run a canned simulation.

**Comment by hol353** [comment]
I'm glad you got it working. Any of the examples will do for an test. I often use the wheat example.

**Comment by wronk** [comment]
The example almost runs, but has one hangup. In the `Examples/Wheat.apsimx` file, the weather file is specified as:
`"FileName": "%root%\\Examples\\WeatherFiles\\Dalby.met"`

This file fails to be found, and I believe that happens because the path is in Windows-style format even though the docker image is built off linux. I can make the simulation run if I modify this variable to `"/apsim/Examples/WeatherFiles/Dalby.met"` and bind the `apsim` directory at the docker container's root level. 

I imagine you don't want to modify the wheat example... Should I make a new, linux-friendly copy with this modification? Or am I missing something with how the paths should be specified?

**Comment by wronk** [comment]
Hi @hol353, friendly ping on this ☝️
